name: Deploy to Contabo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to Contabo
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.CONTABO_HOST }}
        username: ${{ secrets.CONTABO_USERNAME }}
        key: ${{ secrets.CONTABO_SSH_KEY }}
        port: 22
        timeout: 60s
        script: |
            cd /var/www/cosmetics
            git reset --hard
            git pull origin main
            npm ci
            npm run build
